<?php

namespace AppBundle\Repository;

/**
 * Course_ModuleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Course_ModuleRepository extends \Doctrine\ORM\EntityRepository
{
}
