<?php

namespace AppBundle\Repository;

/**
 * CoursesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CoursesRepository extends \Doctrine\ORM\EntityRepository
{

    public function testQuery(){
        /*
         * CreateQueryBuilder : constructeur de requêtes
         *
         *
         * méthode reprenant le nom des commande SQL
         *  select
         *      choix des propiétés de l'entité en utilisant l'allias
         *      renvoie un array de array
         *    Where / andWhere / orWhere
         *      à partir de la deuxieme condition : utilisation de andWhere ou orWhere
         *      uutilisation des parametre de requete
         * définir l'alias de l'entité
         *  getQuery : execturion de la requête / appel de cette methode en avant-derniere position
         * récupération des resultats : dernière position
         *  getResult : renvoie un array d'objets
         */

        $query = $this->createQueryBuilder('courseAlias')
            -> select('courseAlias.formations, courseAlias.slug')
            ->where('courseAlias.formations = :nameParam')
            ->andWhere('courseAlias.formations LIKE :likeParam')
            ->setParameters([
                'nameParam' => 'Développeur BackEnd',
                'likeParam' => 'dev%',

            ])
            -> getQuery()
            ->getResult();
        exit(dump($query));

        //retour des resultats
    }


}
